defaults:
    gitRegistry: git.klogsolenopsys.org
    dockerRegistry: registry.klogsolenopsys.org
    helmRegistry: helm.klogsolenopsys.org
    gitRepoName: solenopsys-fluent-bit
    targetImageName: solenopsys-fluent-bit
    buildForArch: "linux/amd64,linux/arm64"
    imageVersion: latest
    helmPackageVersion: latest # todo убрать это

jobs:
  - create-container:
      docker: go_build_x
  - create-helm-package:
      docker: helm_build

pipeline:
  - build-image
  - create-helm-package


