replicasCount: 1
fullName: "alexstorm-hsm-router"
selectorLabel: "alexstorm-hsm-router"


service:
  nodePort: 30007
  httpPort: 80

containers:
  router:
    name: router
    image: registry.solenopsys.org/alexstorm-hsm-router
    pullPolicy: Always
    httpPort: 80
    httpHost: "0.0.0.0"
    servicesPorts: 9999
    serviceAccount: "hc-infra"
